### ISSUE TITLE
Derived Mode

### ISSUE THREAD

**Issue by semperos** [mk0x9/livescript-mode#1]
Is there a reason this doesn't derive from `coffee-mode` available [here](https://github.com/defunkt/coffee-mode), instead of fundamental mode?

**Comment by mk0x9** [comment]
Sure, this should be more appropriate decision, to derive from `coffee-mode` instead of `fundamental-mode`. I just never written any extensions (including major-modes :) ) for Emacs. And haven't used livescript since last icfpc.

Pull requests, forks, new repos with livescript-mode are welcome. I'll try to look into it at weekend.

**Comment by semperos** [comment]
Haven't touched or looked at this in a long time, closing.
